spring.datasource.url: jdbc:mysql://localhost:3306/grocerieslib?useUnicode=true&
  useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: testtest
spring.jpa.hibernate.ddl-auto: none
spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect